/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinigameRouteImport } from './routes/minigame'
import { Route as IndexRouteImport } from './routes/index'

const MinigameRoute = MinigameRouteImport.update({
  id: '/minigame',
  path: '/minigame',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/minigame': typeof MinigameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/minigame': typeof MinigameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/minigame': typeof MinigameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/minigame'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/minigame'
  id: '__root__' | '/' | '/minigame'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinigameRoute: typeof MinigameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minigame': {
      id: '/minigame'
      path: '/minigame'
      fullPath: '/minigame'
      preLoaderRoute: typeof MinigameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinigameRoute: MinigameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
